config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("menu.urls", namespace="menu")),
]

menu/urls.py
from django.urls import path
from menu.views import *
from menu.apps import MenuConfig

app_name = MenuConfig.name

urlpatterns = [
    path("", MenuListView.as_view(), name="index"),
    path("<slug:slug>", MenuDetailView.as_view(), name="view"),
    path("delete/<slug:slug>", MenuDeleteView.as_view(), name="delete"),
]

menu/models.py
from django.db import models
from autoslug import AutoSlugField

class Menu(models.Model):
    name = models.CharField(max_length=100, verbose_name="Название", unique=True)
    parent = models.ForeignKey(
        "self",
        to_field = 'id',
        blank=True,
        null=True,
        on_delete=models.CASCADE,
        verbose_name="Родительская вкладка",
    )
    slug = AutoSlugField(populate_from = 'name', editable = True, blank = False, always_update = True)

    def __str__(self) -> str:
        return f"{self.id} {self.name}"

    class Meta:
        verbose_name = "Меню"
        verbose_name_plural = "Меню"
        ordering = ("name",)

menu/views.py
from typing import Any
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import *
from menu.models import Menu


class MenuListView(ListView):
    model = Menu

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(parent__isnull=True)
        return queryset


class MenuDetailView(DetailView):
    model = Menu

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context_data = super().get_context_data(**kwargs)
        menu = self.object
        parent = menu.parent
        if parent == None:
            siblings = Menu.objects.filter(parent__isnull=True)
        else:
            siblings = Menu.objects.filter(parent=parent.id)
        context_data["siblings"] = siblings
        childs = Menu.objects.filter(parent=menu)
        context_data["childs"] = childs
        return context_data


class MenuDeleteView(DeleteView):
    model = Menu
    success_url = reverse_lazy("menu:index")

menu/templates/menu/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Menu</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" />
  </head>

  <body>
    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
      <h5 class="my-0 mr-md-auto font-weight-normal">Menu</h5>
      <nav class="ms-5">
      </nav>
    </div>


    <div class="container text-center">
        {% block content %}

        {% endblock %}

    </div>

    <script src="{% static 'js/bootstrap.min.js' %}"></script>
  </body>
</html>

menu/templates/menu/menu_confirm_delete.html
{% extends 'menu/base.html' %}

{% block content %}
  <div class="col-12">
    <div class="row text-center">
      <div class="col-12">
        <div class="card">
          <div class="card-body">
            <form method="post">
              {% csrf_token %}
              <div class="row">
                <button type="submit" class="btn btn-outline-danger col-6">Подтвердить</button>
                <a href="{% url 'menu:index' %}" class="btn btn-outline-success col-6">Вернуться</a>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

menu/templates/menu/menu_detail.html
{% extends 'menu/base.html' %}
{% block content %}
  {% for sibling in siblings %}
    <div class="row text-center" style="width: 100%;">
      <div class="col-12">
        <div class="card mb-4 box-shadow">
          <div class="card-header" style="background-color: lightblue;">
            <h4 class="my-0 font-weight-normal">{{ sibling.name|title }}</h4>
          </div>
          <div class="card-body">
            <div class="row">
              <a class="p-2 btn btn-outline-secondary col-6" href="{% url 'menu:view' sibling.slug %}">Подробнее</a>
              <a class="p-2 btn btn-outline-danger col-6" href="{% url 'menu:delete' sibling.slug %}">удалить</a>
            </div>
          </div>
        </div>
      </div>
    </div>
    {% if sibling == menu %}
      {% for child in childs %}
        <div class="row text-center" style="width: 100%;">
          <div class="col-12">
            <div class="card mb-4 box-shadow">
              <div class="card-header">
                <h4 class="my-0 font-weight-normal">{{ child.name|title }}</h4>
              </div>
              <div class="card-body">
                <div class="row">
                  <a class="p-2 btn btn-outline-secondary col-6" href="{% url 'menu:view' child.slug %}">Подробнее</a>
                  <a class="p-2 btn btn-outline-danger col-6" href="{% url 'menu:delete' child.slug %}">удалить</a>
                </div>
              </div>
            </div>
          </div>
        </div>
      {% endfor %}
    {% endif %}
  {% endfor %}
{% endblock %}

menu/templates/menu/menu_list.html
{% extends 'menu/base.html' %}
{% block content %}
  {% for menu in menu_list %}
    <div class="row text-center" style="width: 100%;">
      <div class="col-12">
        <div class="card mb-4 box-shadow">
          <div class="card-header">
            <h4 class="my-0 font-weight-normal">{{ menu.name|title }}</h4>
          </div>
          <div class="card-body">
            <div class="row">
              <a class="p-2 btn btn-outline-success col-6" href="{% url "menu:view" menu.slug%}">Подробнее</a>
              <a class="p-2 btn btn-outline-danger col-6" href="{% url 'menu:delete' menu.slug%}">удалить</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  {% endfor %}
{% endblock %}